spring.application.name=notification-service
server.port=8086
#EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=postgres
spring.datasource.password=sougata
spring.jpa.hibernate.ddl-auto=update
#NOTIFICATION
vapid.public-key=BA-tHhzZs6bxklpv7FJSYbGF7AsyAMcdcNExpvhAvGhxGn_6u02jrCDTbsUAGM3ExvrkoTW57r0MNsg6-3r82Y4
vapid.private-key=21elYzBCI4IlrTvycUVnJRSMvtMFAiGEB_EzH2QiecQ
vapid.subject=mailto:sougata@chat-box.com